package com.oldstats.tracking.diary;

import java.util.List;
import net.runelite.api.gameval.VarPlayerID;

/**
 * Ported from RuneLite's Quest Helper plugin
 * (github.com/Zoinkwiz/quest-helper, under helpers/achievementdiaries/),
 * which uses these same VarPlayer bitset checks
 * ({@code VarplayerRequirement(VarPlayerID.<AREA>_ACHIEVEMENT_DIARY[2], false,
 * bit)}) to decide which diary steps to skip — confirmed by fetching and
 * parsing all 48 of its area/tier source files directly (not guessed or
 * reconstructed from memory). Each area's ~40 tasks are split across two
 * 32-bit varps ({@code _ACHIEVEMENT_DIARY} and {@code ..._ACHIEVEMENT_DIARY2})
 * since one varp doesn't have enough bits.
 *
 * <p>Task names are Quest Helper's own short editorial labels (from its
 * sidebar panel titles, or derived from its internal variable names for the
 * handful of areas that don't set an explicit panel title) — not
 * necessarily byte-identical to the diary journal's own in-game wording.
 * This is a genuinely different data source from
 * {@link com.oldstats.tracking.DiaryTaskTracker}, which reads the journal
 * widget's actual text but only updates when that page is opened in-game;
 * both write to the same event type, so they complement each other.
 *
 * <p>Karamja's easy/medium/hard tiers predate this bitset system entirely —
 * they're tracked via running-count varps with no per-task identity at all
 * (see {@link com.oldstats.tracking.AchievementDiaryTracker}'s Karamja
 * handling) — so they aren't included here. Karamja's Elite tier was added
 * later and does use a bitset varp ({@code VarPlayerID.ATJUN_TASKS_4}) like
 * every other area.
 */
public final class DiaryTaskData {
    private DiaryTaskData() {}

    public static final List<DiaryTaskDef> ALL_TASKS = List.of(
        // ARDOUGNE EASY
        new DiaryTaskDef("ARDOUGNE", "EASY", "Essence Mine", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 0),
        new DiaryTaskDef("ARDOUGNE", "EASY", "Steal Cake", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 1),
        new DiaryTaskDef("ARDOUGNE", "EASY", "Sell Silk", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 2),
        new DiaryTaskDef("ARDOUGNE", "EASY", "Restore Prayer", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 4),
        new DiaryTaskDef("ARDOUGNE", "EASY", "Fishing Trawler", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 5),
        new DiaryTaskDef("ARDOUGNE", "EASY", "Combat Camp", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 6),
        new DiaryTaskDef("ARDOUGNE", "EASY", "Identify Sword", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 7),
        new DiaryTaskDef("ARDOUGNE", "EASY", "Wilderness Lever", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 9),
        new DiaryTaskDef("ARDOUGNE", "EASY", "Aleck's Hunter Emporium", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 11),
        new DiaryTaskDef("ARDOUGNE", "EASY", "Pet Insurance", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 12),
        // ARDOUGNE MEDIUM
        new DiaryTaskDef("ARDOUGNE", "MEDIUM", "Uni Pen", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 13),
        new DiaryTaskDef("ARDOUGNE", "MEDIUM", "Grap Yan", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 14),
        new DiaryTaskDef("ARDOUGNE", "MEDIUM", "Ardy Straw", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 15),
        new DiaryTaskDef("ARDOUGNE", "MEDIUM", "Teleport Ardy", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 16),
        new DiaryTaskDef("ARDOUGNE", "MEDIUM", "Balloon CW", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 17),
        new DiaryTaskDef("ARDOUGNE", "MEDIUM", "Claim Sand", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 18),
        new DiaryTaskDef("ARDOUGNE", "MEDIUM", "Fishing On Platform", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 19),
        new DiaryTaskDef("ARDOUGNE", "MEDIUM", "Pick Master Farmer", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 20),
        new DiaryTaskDef("ARDOUGNE", "MEDIUM", "Cave Nightshade", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 21),
        new DiaryTaskDef("ARDOUGNE", "MEDIUM", "Kill Swordchick", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 23),
        new DiaryTaskDef("ARDOUGNE", "MEDIUM", "Iban Upgrade", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 24),
        new DiaryTaskDef("ARDOUGNE", "MEDIUM", "Necro Tower", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 25),
        // ARDOUGNE HARD
        new DiaryTaskDef("ARDOUGNE", "HARD", "Recharge", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 26),
        new DiaryTaskDef("ARDOUGNE", "HARD", "Magic Guild", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 27),
        new DiaryTaskDef("ARDOUGNE", "HARD", "Steal Chest", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 28),
        new DiaryTaskDef("ARDOUGNE", "HARD", "Monkey Cage", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 29),
        new DiaryTaskDef("ARDOUGNE", "HARD", "Teleport Watchtower", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 30),
        new DiaryTaskDef("ARDOUGNE", "HARD", "Red Sally", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY, 31),
        new DiaryTaskDef("ARDOUGNE", "HARD", "Palm Tree", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY2, 0),
        new DiaryTaskDef("ARDOUGNE", "HARD", "Poison Ivy", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY2, 1),
        new DiaryTaskDef("ARDOUGNE", "HARD", "Mithril Plate", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY2, 2),
        new DiaryTaskDef("ARDOUGNE", "HARD", "Yan POH", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY2, 3),
        new DiaryTaskDef("ARDOUGNE", "HARD", "Drag Square", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY2, 4),
        new DiaryTaskDef("ARDOUGNE", "HARD", "Death Rune", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY2, 5),
        // ARDOUGNE ELITE
        new DiaryTaskDef("ARDOUGNE", "ELITE", "Trawler Ray", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY2, 6),
        new DiaryTaskDef("ARDOUGNE", "ELITE", "Yan Agility", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY2, 7),
        new DiaryTaskDef("ARDOUGNE", "ELITE", "Rune Crossbow", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY2, 8),
        new DiaryTaskDef("ARDOUGNE", "ELITE", "Pick Hero", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY2, 9),
        new DiaryTaskDef("ARDOUGNE", "ELITE", "Imbue Salve", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY2, 10),
        new DiaryTaskDef("ARDOUGNE", "ELITE", "Pick Torstol", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY2, 11),
        new DiaryTaskDef("ARDOUGNE", "ELITE", "Ardy Rooftops", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY2, 12),
        new DiaryTaskDef("ARDOUGNE", "ELITE", "Ice Barrage", VarPlayerID.ARDOUNGE_ACHIEVEMENT_DIARY2, 13),
        // DESERT EASY
        new DiaryTaskDef("DESERT", "EASY", "Gold Warbler", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 1),
        new DiaryTaskDef("DESERT", "EASY", "Five Clay", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 2),
        new DiaryTaskDef("DESERT", "EASY", "Enter Kalphite", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 3),
        new DiaryTaskDef("DESERT", "EASY", "Enter Desert", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 4),
        new DiaryTaskDef("DESERT", "EASY", "Kill Vulture", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 5),
        new DiaryTaskDef("DESERT", "EASY", "Nardah Herblore", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 6),
        new DiaryTaskDef("DESERT", "EASY", "Collect Cacti", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 7),
        new DiaryTaskDef("DESERT", "EASY", "Sell Artefact", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 8),
        new DiaryTaskDef("DESERT", "EASY", "Open Sarc", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 9),
        new DiaryTaskDef("DESERT", "EASY", "Cut Cactus", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 10),
        new DiaryTaskDef("DESERT", "EASY", "Magic Carpet", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 11),
        // DESERT MEDIUM
        new DiaryTaskDef("DESERT", "MEDIUM", "Agility Pyramid", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 12),
        new DiaryTaskDef("DESERT", "MEDIUM", "Desert Lizard", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 13),
        new DiaryTaskDef("DESERT", "MEDIUM", "Orange Sally", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 14),
        new DiaryTaskDef("DESERT", "MEDIUM", "Phoenix Feather", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 15),
        new DiaryTaskDef("DESERT", "MEDIUM", "Magic Carpet", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 16),
        new DiaryTaskDef("DESERT", "MEDIUM", "Eagle Travel", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 17),
        new DiaryTaskDef("DESERT", "MEDIUM", "Prayer Elidinis", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 18),
        new DiaryTaskDef("DESERT", "MEDIUM", "Combat Pot", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 19),
        new DiaryTaskDef("DESERT", "MEDIUM", "Teleport Enakhra", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 20),
        new DiaryTaskDef("DESERT", "MEDIUM", "Visit Genie", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 21),
        new DiaryTaskDef("DESERT", "MEDIUM", "Teleport Pollnivneach", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 22),
        new DiaryTaskDef("DESERT", "MEDIUM", "Chop Teak", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 23),
        // DESERT HARD
        new DiaryTaskDef("DESERT", "HARD", "Mena Thug", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 24),
        new DiaryTaskDef("DESERT", "HARD", "Granite", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 25),
        new DiaryTaskDef("DESERT", "HARD", "Refill Waterskin", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 26),
        new DiaryTaskDef("DESERT", "HARD", "Kalphite Queen", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 27),
        new DiaryTaskDef("DESERT", "HARD", "Poll Rooftop", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 28),
        new DiaryTaskDef("DESERT", "HARD", "Kill Dust", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 29),
        new DiaryTaskDef("DESERT", "HARD", "Ancient Magicks", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 30),
        new DiaryTaskDef("DESERT", "HARD", "Kill Locust Rider", VarPlayerID.DESERT_ACHIEVEMENT_DIARY, 31),
        new DiaryTaskDef("DESERT", "HARD", "Burn Yew", VarPlayerID.DESERT_ACHIEVEMENT_DIARY2, 0),
        new DiaryTaskDef("DESERT", "HARD", "Mithril Platebody", VarPlayerID.DESERT_ACHIEVEMENT_DIARY2, 1),
        // DESERT ELITE
        new DiaryTaskDef("DESERT", "ELITE", "Wild Pie", VarPlayerID.DESERT_ACHIEVEMENT_DIARY2, 2),
        new DiaryTaskDef("DESERT", "ELITE", "Ice Barrage", VarPlayerID.DESERT_ACHIEVEMENT_DIARY2, 4),
        new DiaryTaskDef("DESERT", "ELITE", "Dragon Darts", VarPlayerID.DESERT_ACHIEVEMENT_DIARY2, 5),
        new DiaryTaskDef("DESERT", "ELITE", "Talk KQ Head", VarPlayerID.DESERT_ACHIEVEMENT_DIARY2, 6),
        new DiaryTaskDef("DESERT", "ELITE", "Grand Gold Chest", VarPlayerID.DESERT_ACHIEVEMENT_DIARY2, 7),
        new DiaryTaskDef("DESERT", "ELITE", "Restore Prayer", VarPlayerID.DESERT_ACHIEVEMENT_DIARY2, 8),
        // FALADOR EASY
        new DiaryTaskDef("FALADOR", "EASY", "Family Crest", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 0),
        new DiaryTaskDef("FALADOR", "EASY", "Climbed Wall", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 1),
        new DiaryTaskDef("FALADOR", "EASY", "Sarah Farming Shop", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 2),
        new DiaryTaskDef("FALADOR", "EASY", "Got Haircut", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 3),
        new DiaryTaskDef("FALADOR", "EASY", "Filled Water", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 4),
        new DiaryTaskDef("FALADOR", "EASY", "Killed Duck", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 5),
        new DiaryTaskDef("FALADOR", "EASY", "Mind Tiara", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 6),
        new DiaryTaskDef("FALADOR", "EASY", "Entrana", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 7),
        new DiaryTaskDef("FALADOR", "EASY", "Motherload Mine", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 8),
        new DiaryTaskDef("FALADOR", "EASY", "Got Security Book", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 9),
        new DiaryTaskDef("FALADOR", "EASY", "Blurite Limbs", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 10),
        // FALADOR MEDIUM
        new DiaryTaskDef("FALADOR", "MEDIUM", "Lit Lantern", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 11),
        new DiaryTaskDef("FALADOR", "MEDIUM", "Telegrabbed Wine", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 12),
        new DiaryTaskDef("FALADOR", "MEDIUM", "Unlocked Crystal Chest", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 13),
        new DiaryTaskDef("FALADOR", "MEDIUM", "Placed Scarecrow", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 14),
        new DiaryTaskDef("FALADOR", "MEDIUM", "Killed Mogre", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 15),
        new DiaryTaskDef("FALADOR", "MEDIUM", "Visit Rat Pits", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 16),
        new DiaryTaskDef("FALADOR", "MEDIUM", "Grapple North Wall", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 17),
        new DiaryTaskDef("FALADOR", "MEDIUM", "Pickpocket Guard", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 18),
        new DiaryTaskDef("FALADOR", "MEDIUM", "Prayer At Altar", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 20),
        new DiaryTaskDef("FALADOR", "MEDIUM", "Mine Gold", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 21),
        new DiaryTaskDef("FALADOR", "MEDIUM", "Dwarf Shortcut", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 22),
        new DiaryTaskDef("FALADOR", "MEDIUM", "Chop Burn Willow Tav", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 23),
        new DiaryTaskDef("FALADOR", "MEDIUM", "Basket Fal Loom", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 24),
        new DiaryTaskDef("FALADOR", "MEDIUM", "Teleport Falador", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 25),
        // FALADOR HARD
        new DiaryTaskDef("FALADOR", "HARD", "Crafted Mind Runes", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 26),
        new DiaryTaskDef("FALADOR", "HARD", "Changed Family Crest", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 27),
        new DiaryTaskDef("FALADOR", "HARD", "Killed Mole", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 28),
        new DiaryTaskDef("FALADOR", "HARD", "Killed Wyvern", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 29),
        new DiaryTaskDef("FALADOR", "HARD", "Complete Agility Course", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 30),
        new DiaryTaskDef("FALADOR", "HARD", "Enter Mining Guild With Prospector", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY, 31),
        new DiaryTaskDef("FALADOR", "HARD", "Killed Blue Dragon", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY2, 0),
        new DiaryTaskDef("FALADOR", "HARD", "Cracked Wall Safe", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY2, 1),
        new DiaryTaskDef("FALADOR", "HARD", "Prayer Sarim Altar Prosy", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY2, 2),
        new DiaryTaskDef("FALADOR", "HARD", "Enter Warriors Guild", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY2, 3),
        new DiaryTaskDef("FALADOR", "HARD", "Dwarven Helmet Dwarven Mines", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY2, 4),
        // FALADOR ELITE
        new DiaryTaskDef("FALADOR", "ELITE", "Crafted Air Runes", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY2, 5),
        new DiaryTaskDef("FALADOR", "ELITE", "Purchased White2h Sword", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY2, 6),
        new DiaryTaskDef("FALADOR", "ELITE", "Got Magic Roots", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY2, 7),
        new DiaryTaskDef("FALADOR", "ELITE", "Performed Skill Cape Emote", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY2, 8),
        new DiaryTaskDef("FALADOR", "ELITE", "Jumped Over Strange Floor", VarPlayerID.FALADOR_ACHIEVEMENT_DIARY2, 9),
        // FREMENNIK EASY
        new DiaryTaskDef("FREMENNIK", "EASY", "Catch Cerulean", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 1),
        new DiaryTaskDef("FREMENNIK", "EASY", "Change Boots", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 2),
        new DiaryTaskDef("FREMENNIK", "EASY", "Killed Crabs", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 3),
        new DiaryTaskDef("FREMENNIK", "EASY", "Craft Tiara", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 4),
        new DiaryTaskDef("FREMENNIK", "EASY", "Browse Stonemason", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 5),
        new DiaryTaskDef("FREMENNIK", "EASY", "Collect Snape Grass", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 6),
        new DiaryTaskDef("FREMENNIK", "EASY", "Steal Stall", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 7),
        new DiaryTaskDef("FREMENNIK", "EASY", "Fill Bucket", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 8),
        new DiaryTaskDef("FREMENNIK", "EASY", "Enter Troll Stronghold", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 9),
        new DiaryTaskDef("FREMENNIK", "EASY", "Chop And Burn Oak", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 10),
        // FREMENNIK MEDIUM
        new DiaryTaskDef("FREMENNIK", "MEDIUM", "Slay Brine Rat", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 11),
        new DiaryTaskDef("FREMENNIK", "MEDIUM", "Snowy Hunter", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 12),
        new DiaryTaskDef("FREMENNIK", "MEDIUM", "Mine Coal", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 13),
        new DiaryTaskDef("FREMENNIK", "MEDIUM", "Steal Fishing", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 14),
        new DiaryTaskDef("FREMENNIK", "MEDIUM", "Travel Misc", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 15),
        new DiaryTaskDef("FREMENNIK", "MEDIUM", "Snowy Knight", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 17),
        new DiaryTaskDef("FREMENNIK", "MEDIUM", "Pet Rock POH", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 18),
        new DiaryTaskDef("FREMENNIK", "MEDIUM", "Lighthouse", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 19),
        new DiaryTaskDef("FREMENNIK", "MEDIUM", "Mine Gold", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 20),
        // FREMENNIK HARD
        new DiaryTaskDef("FREMENNIK", "HARD", "Teleport Troll", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 21),
        new DiaryTaskDef("FREMENNIK", "HARD", "Catch Kyatt", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 23),
        new DiaryTaskDef("FREMENNIK", "HARD", "Mix Super Defence", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 24),
        new DiaryTaskDef("FREMENNIK", "HARD", "Steal Gem", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 25),
        new DiaryTaskDef("FREMENNIK", "HARD", "Craft Shield", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 26),
        new DiaryTaskDef("FREMENNIK", "HARD", "Mine Addy", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 27),
        new DiaryTaskDef("FREMENNIK", "HARD", "Misc Support", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 28),
        new DiaryTaskDef("FREMENNIK", "HARD", "Teleport Waterbirth", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 29),
        new DiaryTaskDef("FREMENNIK", "HARD", "Free Blast", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 30),
        // FREMENNIK ELITE
        new DiaryTaskDef("FREMENNIK", "ELITE", "Dag Kings", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY, 31),
        new DiaryTaskDef("FREMENNIK", "ELITE", "Astral Runes", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY2, 0),
        new DiaryTaskDef("FREMENNIK", "ELITE", "Dragon Amulet", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY2, 1),
        new DiaryTaskDef("FREMENNIK", "ELITE", "Rell Rooftop", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY2, 2),
        new DiaryTaskDef("FREMENNIK", "ELITE", "Godwars Generals", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY2, 3),
        new DiaryTaskDef("FREMENNIK", "ELITE", "Spiritual Mage", VarPlayerID.FREMENNIK_ACHIEVEMENT_DIARY2, 4),
        // KANDARIN EASY
        new DiaryTaskDef("KANDARIN", "EASY", "Catch Mackerel", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 1),
        new DiaryTaskDef("KANDARIN", "EASY", "Buy Candle", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 2),
        new DiaryTaskDef("KANDARIN", "EASY", "Collect Flax", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 3),
        new DiaryTaskDef("KANDARIN", "EASY", "Play Organ", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 4),
        new DiaryTaskDef("KANDARIN", "EASY", "Plant Jute", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 5),
        new DiaryTaskDef("KANDARIN", "EASY", "Cup Tea", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 6),
        new DiaryTaskDef("KANDARIN", "EASY", "Kill Ele", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 7),
        new DiaryTaskDef("KANDARIN", "EASY", "Buy Stew", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 9),
        new DiaryTaskDef("KANDARIN", "EASY", "Talk Sherlock", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 10),
        new DiaryTaskDef("KANDARIN", "EASY", "Log Shortcut", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 11),
        // KANDARIN MEDIUM
        new DiaryTaskDef("KANDARIN", "MEDIUM", "Barb Agility", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 12),
        new DiaryTaskDef("KANDARIN", "MEDIUM", "Super Anti", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 13),
        new DiaryTaskDef("KANDARIN", "MEDIUM", "Enter Range", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 14),
        new DiaryTaskDef("KANDARIN", "MEDIUM", "Grap Ob", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 15),
        new DiaryTaskDef("KANDARIN", "MEDIUM", "Catch Cook Bass", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 16),
        new DiaryTaskDef("KANDARIN", "MEDIUM", "Teleport Cam", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 17),
        new DiaryTaskDef("KANDARIN", "MEDIUM", "String Maple", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 18),
        new DiaryTaskDef("KANDARIN", "MEDIUM", "Pick Limp", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 19),
        new DiaryTaskDef("KANDARIN", "MEDIUM", "Mind Helm", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 20),
        new DiaryTaskDef("KANDARIN", "MEDIUM", "Fire Giant", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 21),
        new DiaryTaskDef("KANDARIN", "MEDIUM", "Barb Ass", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 22),
        new DiaryTaskDef("KANDARIN", "MEDIUM", "Steal Hemen", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 23),
        new DiaryTaskDef("KANDARIN", "MEDIUM", "Travel Mc Grubor", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 24),
        new DiaryTaskDef("KANDARIN", "MEDIUM", "Mine Coal", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 25),
        // KANDARIN HARD
        new DiaryTaskDef("KANDARIN", "HARD", "Catch Sturgeon", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 26),
        new DiaryTaskDef("KANDARIN", "HARD", "Seers Rooftop", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 27),
        new DiaryTaskDef("KANDARIN", "HARD", "Yew Long", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 28),
        new DiaryTaskDef("KANDARIN", "HARD", "Piety Court", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 29),
        new DiaryTaskDef("KANDARIN", "HARD", "Water Orb", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 30),
        new DiaryTaskDef("KANDARIN", "HARD", "Burn Maple", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY, 31),
        new DiaryTaskDef("KANDARIN", "HARD", "Shadow Hound", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY2, 0),
        new DiaryTaskDef("KANDARIN", "HARD", "Mithril Drag", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY2, 1),
        new DiaryTaskDef("KANDARIN", "HARD", "Buy Granite", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY2, 2),
        new DiaryTaskDef("KANDARIN", "HARD", "Fancy Stone", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY2, 3),
        new DiaryTaskDef("KANDARIN", "HARD", "Addy Spear", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY2, 4),
        // KANDARIN ELITE
        new DiaryTaskDef("KANDARIN", "ELITE", "Barb5", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY2, 5),
        new DiaryTaskDef("KANDARIN", "ELITE", "Pick Dwarf", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY2, 6),
        new DiaryTaskDef("KANDARIN", "ELITE", "5 Shark", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY2, 7),
        new DiaryTaskDef("KANDARIN", "ELITE", "Stam Mix", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY2, 8),
        new DiaryTaskDef("KANDARIN", "ELITE", "Rune Hasta", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY2, 9),
        new DiaryTaskDef("KANDARIN", "ELITE", "Pyre", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY2, 10),
        new DiaryTaskDef("KANDARIN", "ELITE", "Teleport Cath", VarPlayerID.KANDARIN_ACHIEVEMENT_DIARY2, 11),
        // KARAMJA ELITE
        new DiaryTaskDef("KARAMJA", "ELITE", "Crafted Runes", VarPlayerID.ATJUN_TASKS_4, 1),
        new DiaryTaskDef("KARAMJA", "ELITE", "Equipped Cape", VarPlayerID.ATJUN_TASKS_4, 2),
        new DiaryTaskDef("KARAMJA", "ELITE", "Checked Palm", VarPlayerID.ATJUN_TASKS_4, 3),
        new DiaryTaskDef("KARAMJA", "ELITE", "Made Potion", VarPlayerID.ATJUN_TASKS_4, 4),
        new DiaryTaskDef("KARAMJA", "ELITE", "Checked Calquat", VarPlayerID.ATJUN_TASKS_4, 5),
        // KOUREND EASY
        new DiaryTaskDef("KOUREND", "EASY", "Mine Iron", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 1),
        new DiaryTaskDef("KOUREND", "EASY", "Sand Crab", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 2),
        new DiaryTaskDef("KOUREND", "EASY", "Arceuus Book", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 3),
        new DiaryTaskDef("KOUREND", "EASY", "Steal Fruit", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 4),
        new DiaryTaskDef("KOUREND", "EASY", "Warrens Store", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 5),
        new DiaryTaskDef("KOUREND", "EASY", "Boat Lands End", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 6),
        new DiaryTaskDef("KOUREND", "EASY", "Prayer Castle", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 7),
        new DiaryTaskDef("KOUREND", "EASY", "Dig Saltpetre", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 8),
        new DiaryTaskDef("KOUREND", "EASY", "Enter Poh", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 9),
        new DiaryTaskDef("KOUREND", "EASY", "Done Agility Course", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 10),
        new DiaryTaskDef("KOUREND", "EASY", "Strength Potion", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 11),
        new DiaryTaskDef("KOUREND", "EASY", "Fishing Trout", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 12),
        // KOUREND MEDIUM
        new DiaryTaskDef("KOUREND", "MEDIUM", "Kill Lizardman", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 13),
        new DiaryTaskDef("KOUREND", "MEDIUM", "Travel With Memoirs", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 14),
        new DiaryTaskDef("KOUREND", "MEDIUM", "Mine Sulphur", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 15),
        new DiaryTaskDef("KOUREND", "MEDIUM", "Switch Spellbooks", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 16),
        new DiaryTaskDef("KOUREND", "MEDIUM", "Repair Crane", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 17),
        new DiaryTaskDef("KOUREND", "MEDIUM", "Deliver Intelligence", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 18),
        new DiaryTaskDef("KOUREND", "MEDIUM", "Catch Bluegill", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 19),
        new DiaryTaskDef("KOUREND", "MEDIUM", "Subdue Wintertodt", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 20),
        new DiaryTaskDef("KOUREND", "MEDIUM", "Enter Farming Guild", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 21),
        new DiaryTaskDef("KOUREND", "MEDIUM", "Use Boulder Shortcut", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 22),
        new DiaryTaskDef("KOUREND", "MEDIUM", "Catch Chinchompa", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 23),
        new DiaryTaskDef("KOUREND", "MEDIUM", "Chop Mahogany Tree", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 24),
        new DiaryTaskDef("KOUREND", "MEDIUM", "Fairy Ring", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 25),
        // KOUREND HARD
        new DiaryTaskDef("KOUREND", "HARD", "Woodcutting Guild", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 26),
        new DiaryTaskDef("KOUREND", "HARD", "Smelt Addy Bar", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 27),
        new DiaryTaskDef("KOUREND", "HARD", "Kill Lizardman Shaman", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 28),
        new DiaryTaskDef("KOUREND", "HARD", "Mine Lovakite", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 29),
        new DiaryTaskDef("KOUREND", "HARD", "Kill Zombie", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 30),
        new DiaryTaskDef("KOUREND", "HARD", "Plant Logavano", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY, 31),
        new DiaryTaskDef("KOUREND", "HARD", "Teleport Heart", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY2, 0),
        new DiaryTaskDef("KOUREND", "HARD", "Deliver Artifact", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY2, 1),
        new DiaryTaskDef("KOUREND", "HARD", "Kill Wyrm", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY2, 2),
        new DiaryTaskDef("KOUREND", "HARD", "Examine Monster", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY2, 3),
        // KOUREND ELITE
        new DiaryTaskDef("KOUREND", "ELITE", "Craft Blood Rune", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY2, 4),
        new DiaryTaskDef("KOUREND", "ELITE", "Chop Redwood", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY2, 5),
        new DiaryTaskDef("KOUREND", "ELITE", "Defeat Skotizo", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY2, 6),
        new DiaryTaskDef("KOUREND", "ELITE", "Catch Angler", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY2, 7),
        new DiaryTaskDef("KOUREND", "ELITE", "Kill Hydra", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY2, 8),
        new DiaryTaskDef("KOUREND", "ELITE", "Create Teleport", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY2, 9),
        new DiaryTaskDef("KOUREND", "ELITE", "Complete Raid", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY2, 10),
        new DiaryTaskDef("KOUREND", "ELITE", "Fletch Battlestaff", VarPlayerID.KOUREND_ACHIEVEMENT_DIARY2, 11),
        // LUMBRIDGE EASY
        new DiaryTaskDef("LUMBRIDGE", "EASY", "Dray Agility", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 1),
        new DiaryTaskDef("LUMBRIDGE", "EASY", "Kill Cave Bug", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 2),
        new DiaryTaskDef("LUMBRIDGE", "EASY", "Sedridor", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 3),
        new DiaryTaskDef("LUMBRIDGE", "EASY", "Water Rune", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 4),
        new DiaryTaskDef("LUMBRIDGE", "EASY", "Hans", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 5),
        new DiaryTaskDef("LUMBRIDGE", "EASY", "Pickpocket", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 6),
        new DiaryTaskDef("LUMBRIDGE", "EASY", "Oak", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 7),
        new DiaryTaskDef("LUMBRIDGE", "EASY", "Kill Zombie", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 8),
        new DiaryTaskDef("LUMBRIDGE", "EASY", "Fishing Anchovies", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 9),
        new DiaryTaskDef("LUMBRIDGE", "EASY", "Bread", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 10),
        new DiaryTaskDef("LUMBRIDGE", "EASY", "Iron", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 11),
        new DiaryTaskDef("LUMBRIDGE", "EASY", "Enter HAM", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 12),
        // LUMBRIDGE MEDIUM
        new DiaryTaskDef("LUMBRIDGE", "MEDIUM", "Al Kharid Rooftop", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 13),
        new DiaryTaskDef("LUMBRIDGE", "MEDIUM", "Grapple Lum", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 14),
        new DiaryTaskDef("LUMBRIDGE", "MEDIUM", "Upgrade Device", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 15),
        new DiaryTaskDef("LUMBRIDGE", "MEDIUM", "Wizard Fairy", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 16),
        new DiaryTaskDef("LUMBRIDGE", "MEDIUM", "T Plumb", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 17),
        new DiaryTaskDef("LUMBRIDGE", "MEDIUM", "Catch Salmon", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 18),
        new DiaryTaskDef("LUMBRIDGE", "MEDIUM", "Craft Coif", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 19),
        new DiaryTaskDef("LUMBRIDGE", "MEDIUM", "Chop Willow", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 20),
        new DiaryTaskDef("LUMBRIDGE", "MEDIUM", "Pick Gardener", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 21),
        new DiaryTaskDef("LUMBRIDGE", "MEDIUM", "Chaeldar Task", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 22),
        new DiaryTaskDef("LUMBRIDGE", "MEDIUM", "Puro Imp", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 23),
        new DiaryTaskDef("LUMBRIDGE", "MEDIUM", "Craft Lava", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 24),
        // LUMBRIDGE HARD
        new DiaryTaskDef("LUMBRIDGE", "HARD", "Bones To Peaches Palace", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 25),
        new DiaryTaskDef("LUMBRIDGE", "HARD", "Jutting Wall", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 26),
        new DiaryTaskDef("LUMBRIDGE", "HARD", "Cosmics", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 27),
        new DiaryTaskDef("LUMBRIDGE", "HARD", "Waka To Edge", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 28),
        new DiaryTaskDef("LUMBRIDGE", "HARD", "Hundred Tears", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 29),
        new DiaryTaskDef("LUMBRIDGE", "HARD", "Train To Keld", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 30),
        new DiaryTaskDef("LUMBRIDGE", "HARD", "Barrows Gloves", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY, 31),
        new DiaryTaskDef("LUMBRIDGE", "HARD", "Belladonna", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY2, 0),
        new DiaryTaskDef("LUMBRIDGE", "HARD", "Light Mining Helm", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY2, 1),
        new DiaryTaskDef("LUMBRIDGE", "HARD", "Smite Altar", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY2, 2),
        new DiaryTaskDef("LUMBRIDGE", "HARD", "Power Ammy", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY2, 3),
        // LUMBRIDGE ELITE
        new DiaryTaskDef("LUMBRIDGE", "ELITE", "Rich Chest", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY2, 4),
        new DiaryTaskDef("LUMBRIDGE", "ELITE", "Grapple Pylon", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY2, 5),
        new DiaryTaskDef("LUMBRIDGE", "ELITE", "Chop Magic", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY2, 6),
        new DiaryTaskDef("LUMBRIDGE", "ELITE", "Addy Platebody", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY2, 7),
        new DiaryTaskDef("LUMBRIDGE", "ELITE", "Water Runes", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY2, 8),
        new DiaryTaskDef("LUMBRIDGE", "ELITE", "QC Emote", VarPlayerID.LUMB_DRAY_ACHIEVEMENT_DIARY2, 9),
        // MORYTANIA EASY
        new DiaryTaskDef("MORYTANIA", "EASY", "Craft Snelm", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 1),
        new DiaryTaskDef("MORYTANIA", "EASY", "Cook Snail", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 2),
        new DiaryTaskDef("MORYTANIA", "EASY", "Mazchna", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 3),
        new DiaryTaskDef("MORYTANIA", "EASY", "Kill Banshee", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 4),
        new DiaryTaskDef("MORYTANIA", "EASY", "Sbott Tan", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 5),
        new DiaryTaskDef("MORYTANIA", "EASY", "Enter Swamp", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 6),
        new DiaryTaskDef("MORYTANIA", "EASY", "Kill Ghoul", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 7),
        new DiaryTaskDef("MORYTANIA", "EASY", "Place Scarecrow", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 8),
        new DiaryTaskDef("MORYTANIA", "EASY", "Offer Bonemeal", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 9),
        new DiaryTaskDef("MORYTANIA", "EASY", "Kill Werewolf", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 10),
        new DiaryTaskDef("MORYTANIA", "EASY", "Restore Prayer", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 11),
        // MORYTANIA MEDIUM
        new DiaryTaskDef("MORYTANIA", "MEDIUM", "Swamp Lizard", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 12),
        new DiaryTaskDef("MORYTANIA", "MEDIUM", "Canifis Agility", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 13),
        new DiaryTaskDef("MORYTANIA", "MEDIUM", "Hollow Tree", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 14),
        new DiaryTaskDef("MORYTANIA", "MEDIUM", "Dragontooth Island", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 15),
        new DiaryTaskDef("MORYTANIA", "MEDIUM", "Terror Dog", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 16),
        new DiaryTaskDef("MORYTANIA", "MEDIUM", "Trouble Brewing", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 17),
        new DiaryTaskDef("MORYTANIA", "MEDIUM", "Swamp Boaty", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 18),
        new DiaryTaskDef("MORYTANIA", "MEDIUM", "Cannon Ball", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 19),
        new DiaryTaskDef("MORYTANIA", "MEDIUM", "Fever Spider", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 20),
        new DiaryTaskDef("MORYTANIA", "MEDIUM", "Ectophial Teleport", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 21),
        new DiaryTaskDef("MORYTANIA", "MEDIUM", "Guth Balance", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 22),
        // MORYTANIA HARD
        new DiaryTaskDef("MORYTANIA", "HARD", "Kharyrll", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 23),
        new DiaryTaskDef("MORYTANIA", "HARD", "Advanced Spikes", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 24),
        new DiaryTaskDef("MORYTANIA", "HARD", "Harvest Watermelon", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 25),
        new DiaryTaskDef("MORYTANIA", "HARD", "Burn Maho", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 26),
        new DiaryTaskDef("MORYTANIA", "HARD", "Hard Temple Trekk", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 27),
        new DiaryTaskDef("MORYTANIA", "HARD", "Cave Horror", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 28),
        new DiaryTaskDef("MORYTANIA", "HARD", "Bittercap Mush", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 29),
        new DiaryTaskDef("MORYTANIA", "HARD", "Piety Altar", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY, 30),
        new DiaryTaskDef("MORYTANIA", "HARD", "Bridge Salve", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY2, 1),
        new DiaryTaskDef("MORYTANIA", "HARD", "Mithril Ore", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY2, 2),
        // MORYTANIA ELITE
        new DiaryTaskDef("MORYTANIA", "ELITE", "Bare Hand Shark", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY2, 3),
        new DiaryTaskDef("MORYTANIA", "ELITE", "Cremate Shade", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY2, 4),
        new DiaryTaskDef("MORYTANIA", "ELITE", "Fertilize Herblore", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY2, 5),
        new DiaryTaskDef("MORYTANIA", "ELITE", "Craft Black Dhide Body", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY2, 6),
        new DiaryTaskDef("MORYTANIA", "ELITE", "Abyssal Demon", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY2, 7),
        new DiaryTaskDef("MORYTANIA", "ELITE", "Barrows Chest", VarPlayerID.MORYTANIA_ACHIEVEMENT_DIARY2, 8),
        // VARROCK EASY
        new DiaryTaskDef("VARROCK", "EASY", "Thessalia", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 1),
        new DiaryTaskDef("VARROCK", "EASY", "Aubury", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 2),
        new DiaryTaskDef("VARROCK", "EASY", "Iron", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 3),
        new DiaryTaskDef("VARROCK", "EASY", "Plank", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 4),
        new DiaryTaskDef("VARROCK", "EASY", "Stronghold Second", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 5),
        new DiaryTaskDef("VARROCK", "EASY", "Fence", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 6),
        new DiaryTaskDef("VARROCK", "EASY", "Dying Tree", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 7),
        new DiaryTaskDef("VARROCK", "EASY", "News", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 8),
        new DiaryTaskDef("VARROCK", "EASY", "Dog Bone", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 9),
        new DiaryTaskDef("VARROCK", "EASY", "Bowl", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 10),
        new DiaryTaskDef("VARROCK", "EASY", "Kudos", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 11),
        new DiaryTaskDef("VARROCK", "EASY", "Earth Rune", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 12),
        new DiaryTaskDef("VARROCK", "EASY", "Trout", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 13),
        new DiaryTaskDef("VARROCK", "EASY", "Tea Stall", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 14),
        // VARROCK MEDIUM
        new DiaryTaskDef("VARROCK", "MEDIUM", "Apoth Strength", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 15),
        new DiaryTaskDef("VARROCK", "MEDIUM", "Champs", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 16),
        new DiaryTaskDef("VARROCK", "MEDIUM", "Cat Colour", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 18),
        new DiaryTaskDef("VARROCK", "MEDIUM", "GE Spirit", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 19),
        new DiaryTaskDef("VARROCK", "MEDIUM", "Stronghold Emote", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 20),
        new DiaryTaskDef("VARROCK", "MEDIUM", "Tolna", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 21),
        new DiaryTaskDef("VARROCK", "MEDIUM", "Teleport Digsite", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 22),
        new DiaryTaskDef("VARROCK", "MEDIUM", "Teleport Varrock", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 23),
        new DiaryTaskDef("VARROCK", "MEDIUM", "Vannaka", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 24),
        new DiaryTaskDef("VARROCK", "MEDIUM", "Maho20", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 25),
        new DiaryTaskDef("VARROCK", "MEDIUM", "White Fruit", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 26),
        new DiaryTaskDef("VARROCK", "MEDIUM", "Balloon", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 27),
        new DiaryTaskDef("VARROCK", "MEDIUM", "Varr Agility", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 28),
        // VARROCK HARD
        new DiaryTaskDef("VARROCK", "HARD", "Spotty Cape", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 29),
        new DiaryTaskDef("VARROCK", "HARD", "153 Kudos", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 30),
        new DiaryTaskDef("VARROCK", "HARD", "Wakka Edge", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY, 31),
        new DiaryTaskDef("VARROCK", "HARD", "Paddewwa Teleport", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY2, 0),
        new DiaryTaskDef("VARROCK", "HARD", "Skull Sceptre", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY2, 1),
        new DiaryTaskDef("VARROCK", "HARD", "Yew Church", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY2, 2),
        new DiaryTaskDef("VARROCK", "HARD", "Fancy Stone", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY2, 3),
        new DiaryTaskDef("VARROCK", "HARD", "Yew Roots", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY2, 4),
        new DiaryTaskDef("VARROCK", "HARD", "Smite Altar", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY2, 5),
        new DiaryTaskDef("VARROCK", "HARD", "Pipe", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY2, 6),
        // VARROCK ELITE
        new DiaryTaskDef("VARROCK", "ELITE", "Super Combat", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY2, 7),
        new DiaryTaskDef("VARROCK", "ELITE", "Plank Make", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY2, 8),
        new DiaryTaskDef("VARROCK", "ELITE", "Summer Pie", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY2, 9),
        new DiaryTaskDef("VARROCK", "ELITE", "Rune Dart", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY2, 10),
        new DiaryTaskDef("VARROCK", "ELITE", "100 Earth", VarPlayerID.VARROCK_ACHIEVEMENT_DIARY2, 11),
        // WESTERN EASY
        new DiaryTaskDef("WESTERN", "EASY", "Copper Longtail", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 1),
        new DiaryTaskDef("WESTERN", "EASY", "Novice Pest", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 2),
        new DiaryTaskDef("WESTERN", "EASY", "Mine Iron", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 3),
        new DiaryTaskDef("WESTERN", "EASY", "Gnome Agility", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 4),
        new DiaryTaskDef("WESTERN", "EASY", "Gnome Ball", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 5),
        new DiaryTaskDef("WESTERN", "EASY", "Chompy Hat", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 6),
        new DiaryTaskDef("WESTERN", "EASY", "Teleport Pest", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 7),
        new DiaryTaskDef("WESTERN", "EASY", "Swamp Toad Collect", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 8),
        new DiaryTaskDef("WESTERN", "EASY", "Brimstail Essence", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 9),
        new DiaryTaskDef("WESTERN", "EASY", "Oak Shortbow", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 10),
        new DiaryTaskDef("WESTERN", "EASY", "Terrorbird", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 11),
        // WESTERN MEDIUM
        new DiaryTaskDef("WESTERN", "MEDIUM", "Agility Shortcut", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 12),
        new DiaryTaskDef("WESTERN", "MEDIUM", "Spirit To Stronghold", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 13),
        new DiaryTaskDef("WESTERN", "MEDIUM", "Spined Larupia", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 14),
        new DiaryTaskDef("WESTERN", "MEDIUM", "Ape Bass", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 15),
        new DiaryTaskDef("WESTERN", "MEDIUM", "Ape Teak", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 16),
        new DiaryTaskDef("WESTERN", "MEDIUM", "Inter Pest", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 17),
        new DiaryTaskDef("WESTERN", "MEDIUM", "Glider To Feldip", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 18),
        new DiaryTaskDef("WESTERN", "MEDIUM", "Chompy Hat", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 19),
        new DiaryTaskDef("WESTERN", "MEDIUM", "Eagle Feldip", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 20),
        new DiaryTaskDef("WESTERN", "MEDIUM", "Chocolate Bomb", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 21),
        new DiaryTaskDef("WESTERN", "MEDIUM", "Gnome Delivery", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 22),
        new DiaryTaskDef("WESTERN", "MEDIUM", "Crystal Saw", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 23),
        new DiaryTaskDef("WESTERN", "MEDIUM", "Mine Gold", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 24),
        // WESTERN HARD
        new DiaryTaskDef("WESTERN", "HARD", "Elf Cystal Bow", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 25),
        new DiaryTaskDef("WESTERN", "HARD", "Monkfish Pisc", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 26),
        new DiaryTaskDef("WESTERN", "HARD", "Vet Pest", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 27),
        new DiaryTaskDef("WESTERN", "HARD", "Dashing Kebbit", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 28),
        new DiaryTaskDef("WESTERN", "HARD", "Ape Atoll Agility", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 29),
        new DiaryTaskDef("WESTERN", "HARD", "Mahogany Burned", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 30),
        new DiaryTaskDef("WESTERN", "HARD", "Mine Addy Ore", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY, 31),
        new DiaryTaskDef("WESTERN", "HARD", "Lletya Palm", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY2, 0),
        new DiaryTaskDef("WESTERN", "HARD", "Chompy Hat", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY2, 1),
        new DiaryTaskDef("WESTERN", "HARD", "Isafdar Painting", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY2, 2),
        new DiaryTaskDef("WESTERN", "HARD", "Kill Zulrah", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY2, 3),
        new DiaryTaskDef("WESTERN", "HARD", "Teleport Ape", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY2, 4),
        new DiaryTaskDef("WESTERN", "HARD", "Pickpocket Gnome", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY2, 5),
        // WESTERN ELITE
        new DiaryTaskDef("WESTERN", "ELITE", "Magic Long", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY2, 6),
        new DiaryTaskDef("WESTERN", "ELITE", "Kill Thermy", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY2, 7),
        new DiaryTaskDef("WESTERN", "ELITE", "Prissy Scilla", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY2, 8),
        new DiaryTaskDef("WESTERN", "ELITE", "Advanced Agility", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY2, 9),
        new DiaryTaskDef("WESTERN", "ELITE", "Full Void", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY2, 12),
        new DiaryTaskDef("WESTERN", "ELITE", "Chompy Hat", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY2, 13),
        new DiaryTaskDef("WESTERN", "ELITE", "Pickpocket Elf", VarPlayerID.WESTERN_ACHIEVEMENT_DIARY2, 14),
        // WILDERNESS EASY
        new DiaryTaskDef("WILDERNESS", "EASY", "Low Alch", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 1),
        new DiaryTaskDef("WILDERNESS", "EASY", "Wildy Lever", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 2),
        new DiaryTaskDef("WILDERNESS", "EASY", "Chaos Altar", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 3),
        new DiaryTaskDef("WILDERNESS", "EASY", "Chaos Temple", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 4),
        new DiaryTaskDef("WILDERNESS", "EASY", "Kill Mammoth", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 5),
        new DiaryTaskDef("WILDERNESS", "EASY", "Earth Warrior", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 6),
        new DiaryTaskDef("WILDERNESS", "EASY", "Demonic Prayer", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 7),
        new DiaryTaskDef("WILDERNESS", "EASY", "Enter KBD Lair", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 8),
        new DiaryTaskDef("WILDERNESS", "EASY", "Spider Eggs", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 9),
        new DiaryTaskDef("WILDERNESS", "EASY", "Iron Ore", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 10),
        new DiaryTaskDef("WILDERNESS", "EASY", "Enter Abyss", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 11),
        new DiaryTaskDef("WILDERNESS", "EASY", "Equip Team Cape", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 12),
        // WILDERNESS MEDIUM
        new DiaryTaskDef("WILDERNESS", "MEDIUM", "Mine Mithril", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 13),
        new DiaryTaskDef("WILDERNESS", "MEDIUM", "Ent Yew", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 14),
        new DiaryTaskDef("WILDERNESS", "MEDIUM", "Wildy God Wars", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 15),
        new DiaryTaskDef("WILDERNESS", "MEDIUM", "Wildy Agility", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 16),
        new DiaryTaskDef("WILDERNESS", "MEDIUM", "Kill Green Drag", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 18),
        new DiaryTaskDef("WILDERNESS", "MEDIUM", "Kill Ankou", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 19),
        new DiaryTaskDef("WILDERNESS", "MEDIUM", "Earth Orb", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 20),
        new DiaryTaskDef("WILDERNESS", "MEDIUM", "Wildy GW Bloodveld", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 21),
        new DiaryTaskDef("WILDERNESS", "MEDIUM", "Emblem Trader", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 22),
        new DiaryTaskDef("WILDERNESS", "MEDIUM", "Gold Helm", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 23),
        new DiaryTaskDef("WILDERNESS", "MEDIUM", "Muddy Chest", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 24),
        // WILDERNESS HARD
        new DiaryTaskDef("WILDERNESS", "HARD", "God Spells", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 25),
        new DiaryTaskDef("WILDERNESS", "HARD", "Air Orb", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 26),
        new DiaryTaskDef("WILDERNESS", "HARD", "Black Sally", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 27),
        new DiaryTaskDef("WILDERNESS", "HARD", "Addy Scim", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 28),
        new DiaryTaskDef("WILDERNESS", "HARD", "Lava Drag", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 29),
        new DiaryTaskDef("WILDERNESS", "HARD", "Chaos Ele", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 30),
        new DiaryTaskDef("WILDERNESS", "HARD", "Three Bosses", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY, 31),
        new DiaryTaskDef("WILDERNESS", "HARD", "Troll Wildy", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY2, 0),
        new DiaryTaskDef("WILDERNESS", "HARD", "Sprirtual Warrior", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY2, 1),
        new DiaryTaskDef("WILDERNESS", "HARD", "Raw Lava Eel", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY2, 2),
        // WILDERNESS ELITE
        new DiaryTaskDef("WILDERNESS", "ELITE", "Three Bosses", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY2, 3),
        new DiaryTaskDef("WILDERNESS", "ELITE", "Teleport Ghorrock", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY2, 5),
        new DiaryTaskDef("WILDERNESS", "ELITE", "Dark Crab", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY2, 7),
        new DiaryTaskDef("WILDERNESS", "ELITE", "Rune Scim", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY2, 8),
        new DiaryTaskDef("WILDERNESS", "ELITE", "Rogues Chest", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY2, 9),
        new DiaryTaskDef("WILDERNESS", "ELITE", "Spirit Mage", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY2, 10),
        new DiaryTaskDef("WILDERNESS", "ELITE", "Magic Logs", VarPlayerID.WILDERNESS_ACHIEVEMENT_DIARY2, 11)
    );
}
