package com.oldstats.tracking.farming

/**
 * Mirrors RuneLite's internal `Produce` enum
 * (net.runelite.client.plugins.timetracking.farming.Produce) — display names
 * only, ported by hand from the decompiled source since that class is
 * package-private and not directly reusable.
 */
enum class Produce(val displayName: String) {
    WEEDS("Weeds"),
    SCARECROW("Scarecrow"),
    POTATO("Potato"),
    ONION("Onion"),
    CABBAGE("Cabbage"),
    TOMATO("Tomato"),
    SWEETCORN("Sweetcorn"),
    STRAWBERRY("Strawberry"),
    WATERMELON("Watermelon"),
    SNAPE_GRASS("Snape grass"),
    MARIGOLD("Marigold"),
    ROSEMARY("Rosemary"),
    NASTURTIUM("Nasturtium"),
    WOAD("Woad"),
    LIMPWURT("Limpwurt"),
    WHITE_LILY("White lily"),
    REDBERRIES("Redberry"),
    CADAVABERRIES("Cadavaberry"),
    DWELLBERRIES("Dwellberry"),
    JANGERBERRIES("Jangerberry"),
    WHITEBERRIES("Whiteberry"),
    POISON_IVY("Poison ivy"),
    BARLEY("Barley"),
    HAMMERSTONE("Hammerstone"),
    ASGARNIAN("Asgarnian"),
    JUTE("Jute"),
    YANILLIAN("Yanillian"),
    FLAX("Flax"),
    KRANDORIAN("Krandorian"),
    WILDBLOOD("Wildblood"),
    HEMP("Hemp"),
    COTTON("Cotton"),
    GUAM("Guam"),
    MARRENTILL("Marrentill"),
    TARROMIN("Tarromin"),
    HARRALANDER("Harralander"),
    RANARR("Ranarr"),
    TOADFLAX("Toadflax"),
    IRIT("Irit"),
    AVANTOE("Avantoe"),
    KWUARM("Kwuarm"),
    HUASCA("Huasca"),
    SNAPDRAGON("Snapdragon"),
    CADANTINE("Cadantine"),
    LANTADYME("Lantadyme"),
    DWARF_WEED("Dwarf weed"),
    TORSTOL("Torstol"),
    GOUTWEED("Goutweed"),
    ANYHERB("Any herb"),
    OAK("Oak"),
    WILLOW("Willow"),
    MAPLE("Maple"),
    YEW("Yew"),
    MAGIC("Magic"),
    APPLE("Apple"),
    BANANA("Banana"),
    ORANGE("Orange"),
    CURRY("Curry"),
    PINEAPPLE("Pineapple"),
    PAPAYA("Papaya"),
    PALM("Palm"),
    DRAGONFRUIT("Dragonfruit"),
    CACTUS("Cactus"),
    POTATO_CACTUS("Potato cactus"),
    TEAK("Teak"),
    MAHOGANY("Mahogany"),
    CAMPHOR("Camphor"),
    IRONWOOD("Ironwood"),
    ROSEWOOD("Rosewood"),
    ATTAS("Attas"),
    IASOR("Iasor"),
    KRONOS("Kronos"),
    ELKHORN_CORAL("Elkhorn"),
    PILLAR_CORAL("Pillar"),
    UMBRAL_CORAL("Umbral"),
    SEAWEED("Seaweed"),
    GRAPE("Grape"),
    MUSHROOM("Mushroom"),
    BELLADONNA("Belladonna"),
    CALQUAT("Calquat"),
    SPIRIT_TREE("Spirit tree"),
    CELASTRUS("Celastrus"),
    REDWOOD("Redwood"),
    HESPORI("Hespori"),
    CRYSTAL_TREE("Crystal tree"),
    EMPTY_COMPOST_BIN("Compost Bin"),
    COMPOST("Compost"),
    SUPERCOMPOST("Supercompost"),
    ULTRACOMPOST("Ultracompost"),
    ROTTEN_TOMATO("Rotten Tomato"),
    EMPTY_BIG_COMPOST_BIN("Big Compost Bin"),
    BIG_COMPOST("Compost"),
    BIG_SUPERCOMPOST("Supercompost"),
    BIG_ULTRACOMPOST("Ultracompost"),
    BIG_ROTTEN_TOMATO("Rotten Tomato"),
}

enum class CropState {
    GROWING,
    HARVESTABLE,
    DISEASED,
    DEAD,
    EMPTY,
    FILLING,
}

data class PatchState(val produce: Produce, val cropState: CropState)
